### PR TITLE
GT Quests for LuV and ZPM Tier

### PR DESCRIPTION
**Pull request by timeconsumer06**
I have gone through and added in Quest chapters for Gregtech LuV and ZPM. Both chapters are full and complete with proper descriptions for each tier, and has all of the required components to guide a player through each tier respectively.

Loot tables have been created for each tier separately as well, balanced the same as the previous tiers, and including similar rewards as the previous tiers just to keep continuity. 

A few images were added to the chapters pages, just to identify it as its respective tier, however those images can easily be adjusted or removed if its desired to not have them.

### CODE REVIEW

**Comment by timeconsumer06** [comment]
Theres 3 commits, as after initially uploading the files I noticed some discrepancies in the Chapters for LuV and ZMP that I did not like, so I made the corrections and re-uploaded the files which added a 3rd commit.

**Comment by Mrminesheeps** [comment]
This would be really cool to have! Something I wish I had when I was dragging myself through LuV and ZPM lol.

**Comment by whatthedrunk** [comment]
Thanks! The team is working on cleaning this up a bit but we plan to add it soon.

**Comment by loving2** [comment]
Looks pretty good to me! I've made some adjustments, mainly layout and size to help keep the footprint of the quest chapters a little smaller for those with lower resolution screens. 

I also took this as an opportunity to do the following:
- removed the forge:ingots/naquadah and forge:ingots/naquadah_alloy item tag from weapons grade naquadah which fixes a GT recipe mix up
- fix thermal series quests (random rewards gave nothing, the lootbag file was in the wrong folder)
- adjusted order of quests so milestones is at the bottom
- removed IV and LuV Processing Array quests
- switched Naq plates for Naq Alloy plates for ZPM machine hulls
- fiddled with general shape/layout

**Review by loving2 — APPROVED** [review]
I made some merge conflicts, but they're resolved now. All looks good to me!

**Comment by timeconsumer06** [comment]
I definitely didnt do this right. I was trying to open up a new PR, and add some new files, but I accidentally committed them to the existing PR. If theres any way to remove the commits i just made, Ill gladly do so, or re-initiate checks on the stuff I dropped in.
The new Files contain the Finished UV Quest line, and UV Rewards Loot table, as well as the UHV Rewards Loot table. UHV quests are not quite finished yet, but will be very soon.

I also dropped in fixes for the following sections that address issues from the 0.2.46 update that caused missing items in quests and rewards loot tables.

Chapters Fixed
Medium Voltage 
Insane voltage

Reward Loot tables fixed
GT MV Basic Rewards
GT HV Basic Rewards
GT EV Basic Rewards

**Comment by loving2** [comment]
No worries! Generally speaking, one would make a new branch, commit and push changes to that branch, then make a PR of that branch. That way a different branch can be made for new changes that won't get pushed to the existing PR. This is still fine though!

I'm a bit confused about the missing items fixes though. It looks like an item like `Small Pile of Gallium Arsenide Dust` changed ID from `gtceu:gallium_arsenide_small_dust` to `gtceu:small_gallium_arsenide_dust`. I thought I had already changed that in this PR, and it looks like you reverted it? I could be reading this wrong though. I'm specifically looking at line 162 in the extreme_voltage.snbt file

**Comment by loving2** [comment]
Perhaps you were working on a previous version of some of the quest files and may have missed a couple of the items while fixing the others? Anyway, all I've done is adjust the order of the milestone chapter and adjust IDs of a couple items here and there. Additionally I committed an update to the order_index value for reward tables so that there are no conflicts there.

**Review by loving2 — APPROVED** [review]
All looks good to me! Approved :)

**Pull request merged**
