### PR TITLE
Add the Mega Fusion Reactor & co.

### PR DESCRIPTION
**Pull request by screret**
adds:
- Mega Fusion Reactor multiblock
- star matter plasma
- fluorite vein in GT

changes:
- practically remove some GT-only chemlib items.
- some more crops

fixes:
- fix MUO multiblock pattern
- fix MUO energy output values slightly being too low

### CODE REVIEW

**Comment by loving2** [comment]
This looks pretty sweet to me, I love the mega fusion reactor - a few things I spotted though
1) the Alchemistry Fusion Core recipe uses tungsten ingots, so maybe we just adjust that recipe to use a different ingot?
2) there's no lang entry for the mega fusion reactor or star matter plasma
3) we should probably shape info the supercharged coils on the mega fusion reactor, at some point lol

**Comment by screret** [comment]
1) oops.
2) big oops.
3) yea I couldn't get it to work right

**Comment by loving2** [comment]
Cool, looks like the new method to the Alchemistry fusion core is to dissolve blue dye into cobalt aluminate, dissolve that into cobalt, compact that into dust, smelt the dust, aaaaaand that doesn't make chemlib:cobalt_ingot... I guess using the `#forge:ingots/cobalt` tag would work? 

I'll probably fiddle with the shape info, at some point, assuming nobody else gets to it first, but yeah I think it is fine to leave off for now

**Comment by loving2** [comment]
Ah, it looks like many of the chemlib bees flower on specifically the chemlib blocks, which are not craftable

1) Yttrium bee cannot be made, requires a chemlib yttrium block
2) Yttrium bee cannot produce combs, needs a chemlib yttrium block
3) Chromium bee cannot produce combs, needs the chemlib chromium block
4) Europium bee
5) Neodymium bee
6) Niobium bee
7) Palladium bee
8) Rhodium bee
9) Ruthenium bee
10) Samarium bee
11) Vanadium bee

These could be changed to just use the elements like `chemlib:yttrium` for flowering/conversion? I think that means they'd need to be simulated and use a feeding slab, but that's probably alright

**Comment by screret** [comment]
- [x] Yttrium bee
- [x] Chromium bee
- [x] Europium bee
- [x] Neodymium bee
- [x] Niobium bee
- [x] Palladium bee
- [x] Rhodium bee
- [x] Ruthenium bee
- [x] Samarium bee
- [x] Vanadium bee

**Review by Drackion — COMMENTED** [review]
looks good but I'll wait to see what the others think about the seeds as i recall a talk about some other ways to balance them, not all but some so they don't need to be disabled

**Comment by loving2** [comment]
Doesn't seem right to require someone making Alchemistry bees to also progress GT just to get the block for the bee to pollinate. Also bee conversion for the Yttrium bee is still broken. 

I can change the flowerTag to flowerItem for the element rather than the storage block and add the conversion json, and once done I think this will be all good!

**Review by loving2 — APPROVED** [review]
All seems to be in working order in a testing world!

**Pull request merged**
