### PR TITLE
Unify Eidolon's Lead and Silver

### PR DESCRIPTION
**Pull request by iarspider**
* Make Eidolon Lead/Silver ores drop AllTheOres Lead/Silver when broken
* Change Eidolon worldgen to spawn AllTheOres Lead/Silver instead of it's own

### CODE REVIEW

**Comment by Mitchell5200** [comment]
Currently not necessary in ATM9, as we have Eidolon ore gen disabled, and the materials unified via Almost unified, smelting the remaining Eidolon raw ores will result in ATO ingots.

Thank you anyway

**Comment by iarspider** [comment]
Out of curiosity - when was this fixed?

**Comment by Mitchell5200** [comment]
pack version 0.2.52, 
Worldgen remove https://github.com/AllTheMods/ATM-9/commit/65943caa8aebc6d06f30a8cdbe1ce40e3ce1584b
Unify, https://github.com/AllTheMods/ATM-9/commit/795f2422c0a9fedb332635923cc2e19f081e5d7b

**Comment by iarspider** [comment]
Thanks!

**Pull request closed without merging**
