### PR TITLE
Add alternative method for harnessing Wasted Radioactive Bees

### PR DESCRIPTION
**Pull request by Mrminesheeps**
Simply put, I made this as an alternative to nuking your world. This is a change mostly for servers but also nice to have as an option that doesn't break progression.

### CODE REVIEW

**Comment by Mrminesheeps** [comment]
It's worth mentioning that I have implemented and tested both of these files, as well as verified original functionality (Wasted bees will still flower with ambient radiation released via destroyed barrel/blown reactor)

**Comment by JaisDK** [comment]
You can't have flowerBlock and flowerTag defined at the same time and if `forge:pellets/antimatter` is an item then you need to add `"flowerType": "item"` or just use `flowerItem` instead of a tag.

**Comment by Mrminesheeps** [comment]
> You can't have flowerBlock and flowerTag defined at the same time and if `forge:pellets/antimatter` is an item then you need to add `"flowerType": "item"` or just use `flowerItem` instead of a tag.

I actually already tested these in a Singleplayer world, both of these files are fully functional. The bees can flower off of radiation AND antimatter pellets without issue.

**Comment by Mrminesheeps** [comment]
Switching things is breaking things; I've removed the flowerBlock line and replaced flowerTag with flowerItem, so now it works again in Singleplayer. But I'm still interested in having both in the JSON for the purposes of maintaining original function whilst still offering this alternative; is there a way to have both?

**Comment by Kevin-Marsh** [comment]
This is being added into productive bees.

**Pull request closed without merging**
